import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { once } from 'node:events';
import { createApp } from '../server.mjs';

test('API persists across restart, rejects stale writes and isolates static files', async t => {
  const dataDir = mkdtempSync(join(tmpdir(), 'procision-test-'));
  let server = createApp({ dataDir });
  const start = async () => { server.listen(0, '127.0.0.1'); await once(server, 'listening'); return `http://127.0.0.1:${server.address().port}`; };
  let url = await start();
  t.after(() => new Promise(resolve => server.close(resolve)));
  const send = (body, headers = {}) => fetch(`${url}/api/commands`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(body) });
  const first = await send({ revision: 0, command: { type: 'create-task', title: '持久保存', description: '多行\n进度', date: '2026-09-30' } });
  assert.equal(first.status, 200);
  let state = await first.json();
  assert.equal(state.tasks[0].title, '持久保存');
  const collision = await send({ revision: 0, command: { type: 'delete-task', taskId: state.tasks[0].id } });
  assert.equal(collision.status, 409);
  assert.equal((await collision.json()).state.tasks.length, 1);
  const foreign = await send({ revision: 1, command: { type: 'delete-task', taskId: state.tasks[0].id } }, { Origin: 'https://example.com' });
  assert.equal(foreign.status, 403);
  assert.equal((await send(null)).status, 400);
  assert.equal((await fetch(`${url}/data/procision.sqlite`)).status, 404);
  assert.equal((await fetch(`${url}/package.json`)).status, 404);
  const backup = readdirSync(join(dataDir, 'backups'));
  assert.equal(backup.length, 1);
  assert.equal(JSON.parse(readFileSync(join(dataDir, 'backups', backup[0]), 'utf8')).revision, 0);
  const statusChange = await send({ revision: state.revision, command: { type: 'set-task-status', taskId: state.tasks[0].id, status: 'active' } });
  assert.equal(statusChange.status, 200);
  state = await statusChange.json();
  assert.equal(state.tasks[0].statusMode, 'manual');
  assert.equal(state.tasks[0].status, 'active');
  await new Promise(resolve => server.close(resolve));
  server = createApp({ dataDir });
  url = await start();
  const recovered = await (await fetch(`${url}/api/state`)).json();
  assert.deepEqual(recovered, state);
  const exported = await fetch(`${url}/api/export`);
  assert.match(exported.headers.get('content-disposition'), /attachment/);
  assert.deepEqual(await exported.json(), state);
  const created = await send({ revision: state.revision, command: { type: 'create-note', title: '新的长期记录', conclusion: '目前的结论', content: '完整思考过程\n保留换行', status: 'thought' } });
  assert.equal(created.status, 200);
  const withNotes = await created.json();
  assert.deepEqual(withNotes.tasks, state.tasks);
  assert.deepEqual(withNotes.activities, state.activities);
  assert.equal(withNotes.notes.length, 1);
  await new Promise(resolve => server.close(resolve));
  server = createApp({ dataDir });
  url = await start();
  assert.deepEqual(await (await fetch(`${url}/api/state`)).json(), withNotes);
  assert.deepEqual(await (await fetch(`${url}/api/export`)).json(), withNotes);
  const conflict = await send({ revision: state.revision, command: { type: 'edit-note', noteId: withNotes.notes[0].id, title: '过期窗口', content: '不能覆盖' } });
  assert.equal(conflict.status, 409);
  assert.deepEqual((await conflict.json()).state, withNotes);
});
