import { test, expect } from '@playwright/test';

test('long notes persist across dates and reloads; editing retains history; archive is reversible', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const before = await (await page.request.get('/api/state')).json();
  await page.goto('/');
  const panel = page.getByRole('region', { name: '思考与结论' });
  await expect(panel).toBeVisible();
  const beforeLayout = await page.locator('.task-workspace').boundingBox();
  await page.getByRole('button', { name: '新建思考记录' }).click();
  await page.getByLabel('记录标题').fill('市场回撤与中心漂移');
  await page.getByRole('textbox', { name: '当前结论' }).fill('提前下调 mu，是否与 caseE 思路一致？');
  const content = '9/30 市场回撤\n原始思考 <script>window.noteInjected = true</script>\n' + '继续保留思考过程。\n'.repeat(400);
  await page.getByLabel('思考过程与有用信息').fill(content);
  await page.getByRole('button', { name: '保存记录', exact: true }).click();
  await expect(panel.getByRole('button', { name: '查看记录：市场回撤与中心漂移' })).toBeVisible();
  await expect(panel.locator('.note-inline-text')).toHaveText('提前下调 mu，是否与 caseE 思路一致？');
  await expect(panel).not.toContainText('原始思考');
  await expect(panel).not.toContainText('思考过程与有用信息');
  const afterLayout = await page.locator('.task-workspace').boundingBox();
  expect(afterLayout.x).toBe(beforeLayout.x);
  expect(afterLayout.y).toBe(beforeLayout.y);
  expect(afterLayout.width).toBe(beforeLayout.width);
  const beforeRight = await page.locator('.insights').boundingBox();
  await page.getByRole('button', { name: '收起日历栏', exact: true }).click();
  await expect.poll(async () => Math.round((await page.locator('.sidebar').boundingBox()).width)).toBe(60);
  const compactRight = await page.locator('.insights').boundingBox();
  const wideCenter = await page.locator('.task-workspace').boundingBox();
  expect(compactRight.width - beforeRight.width).toBeLessThan(55);
  expect(wideCenter.width - afterLayout.width).toBeGreaterThan(100);
  await page.getByRole('button', { name: '前一天' }).click();
  await expect(panel.getByRole('button', { name: '查看记录：市场回撤与中心漂移' })).toBeVisible();
  await page.reload();
  await panel.getByRole('button', { name: '查看记录：市场回撤与中心漂移' }).click();
  await expect(page.locator('.note-reader .note-section').last().locator('.note-text')).toHaveText(content.trim());
  expect(await page.evaluate(() => window.noteInjected)).toBeUndefined();
  await page.getByRole('button', { name: '编辑记录', exact: true }).click();
  await page.getByRole('textbox', { name: '当前结论' }).fill('补充后的结论，仍保留原始思考。');
  await page.getByRole('radio', { name: '当前结论', exact: true }).check();
  await page.getByRole('button', { name: '保存记录', exact: true }).click();
  await panel.getByRole('button', { name: '查看记录：市场回撤与中心漂移' }).click();
  await page.locator('.note-history > summary').click();
  await page.locator('.note-version > summary').click();
  await expect(page.locator('.note-version')).toContainText('提前下调 mu，是否与 caseE 思路一致？');
  await page.getByRole('button', { name: '归档（仍可找回）', exact: true }).click();
  await expect(panel.locator('.note-item')).toHaveCount(0);
  await panel.getByRole('button', { name: '查看归档' }).click();
  await panel.getByRole('button', { name: '查看记录：市场回撤与中心漂移' }).click();
  await page.getByRole('button', { name: '恢复到记录' }).click();
  await panel.getByRole('button', { name: '返回记录' }).click();
  await expect(panel.locator('.note-item')).toHaveCount(1);
  await page.getByLabel('搜索思考与结论').fill('caseE');
  await expect(panel.locator('.note-item')).toHaveCount(0);
  await page.getByLabel('搜索思考与结论').fill('原始思考');
  await expect(panel.locator('.note-item')).toHaveCount(1);
  const after = await (await page.request.get('/api/state')).json();
  expect(after.tasks).toEqual(before.tasks);
  expect(after.activities).toEqual(before.activities);
  expect(errors).toEqual([]);
});

test('failed note saves preserve drafts and stale windows cannot overwrite another edit', async ({ page, context }) => {
  await page.goto('/');
  await page.getByRole('button', { name: '新建思考记录' }).click();
  await page.getByLabel('记录标题').fill('保留草稿');
  await page.getByLabel('思考过程与有用信息').fill('网络中断也要保留。');
  await page.route('**/api/commands', route => route.abort('failed'));
  await page.getByRole('button', { name: '保存记录', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('暂时无法保存');
  await page.getByRole('button', { name: '取消', exact: true }).click();
  await page.getByRole('button', { name: '新建思考记录' }).click();
  await expect(page.getByLabel('思考过程与有用信息')).toHaveText('网络中断也要保留。');
  await page.unroute('**/api/commands');
  await page.getByRole('button', { name: '保存记录', exact: true }).click();
  await page.getByRole('button', { name: '查看记录：保留草稿', exact: true }).click();
  await page.getByRole('button', { name: '编辑记录', exact: true }).click();
  await page.getByRole('textbox', { name: '当前结论' }).fill('窗口 A 的草稿');
  const other = await context.newPage();
  await other.goto('/');
  await other.getByRole('button', { name: '查看记录：保留草稿', exact: true }).click();
  await other.getByRole('button', { name: '编辑记录', exact: true }).click();
  await other.getByRole('textbox', { name: '当前结论' }).fill('窗口 B 已保存的结论');
  await other.getByRole('button', { name: '保存记录', exact: true }).click();
  await page.getByRole('button', { name: '保存记录', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('其他窗口更新了内容');
  await expect(page.getByRole('textbox', { name: '当前结论' })).toHaveText('窗口 A 的草稿');
  const state = await (await page.request.get('/api/state')).json();
  expect(state.notes.find(note => note.title === '保留草稿').conclusion).toBe('窗口 B 已保存的结论');
});
