import { test, expect } from '@playwright/test';
import { localDay } from '../../lib/domain.mjs';

async function seed(page, title) {
  let state = await (await page.request.get('/api/state')).json();
  const run = async command => {
    const response = await page.request.post('/api/commands', { data: { revision: state.revision, command } });
    expect(response.ok()).toBeTruthy(); state = await response.json();
  };
  await run({ type: 'create-task', title, date: localDay() });
  const taskId = state.tasks.at(-1).id;
  await run({ type: 'create-step', taskId, title: '中心调整方向', content: '原来的进度内容保留', status: 'done' });
  await run({ type: 'create-step', taskId, title: '独立验证方向', status: 'done' });
  return taskId;
}

async function removeTask(page, taskId) {
  const state = await (await page.request.get('/api/state')).json();
  const response = await page.request.post('/api/commands', { data: { revision: state.revision, command: { type: 'delete-task', taskId } } });
  expect(response.ok()).toBeTruthy();
}

test('parallel directions contain ordered progress with images, search, rollups and reversible completion', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const taskId = await seed(page, '分方向跟进测试');
  await page.goto('/');
  const task = page.locator(`[data-task-id="${taskId}"]`);
  const direction = task.locator('.step').filter({ has: page.locator('.step-title', { hasText: '中心调整方向' }) });
  const other = task.locator('.step').filter({ has: page.locator('.step-title', { hasText: '独立验证方向' }) });
  await expect(task).toHaveClass(/task-done/);
  await direction.getByRole('button', { name: '添加子进度', exact: true }).click();
  await expect(page.getByLabel('子进度标题')).toBeEmpty();
  await expect(page.getByLabel('进度记录')).toBeEmpty();
  await page.getByLabel('子进度标题').fill('第一轮验证');
  const content = '子进度搜索关键字 <script>window.substepInjected = true</script>\n' + '完整的验证记录\n'.repeat(30);
  await page.getByLabel('进度记录').fill(content);
  await page.locator('#form-content').evaluate(async input => {
    const canvas = document.createElement('canvas'); canvas.width = 320; canvas.height = 160;
    const ctx = canvas.getContext('2d'); ctx.fillStyle = '#22d3ee'; ctx.fillRect(0, 0, 320, 160);
    const blob = await new Promise(resolve => canvas.toBlob(resolve, 'image/png'));
    const clipboard = new DataTransfer(); clipboard.items.add(new File([blob], '子进度截图.png', { type: 'image/png' }));
    input.dispatchEvent(new ClipboardEvent('paste', { clipboardData: clipboard, bubbles: true, cancelable: true }));
  });
  await expect(page.locator('.image-draft-caption')).toContainText('已就绪');
  await page.getByRole('radio', { name: '待跟进', exact: true }).check();
  await page.getByRole('dialog').getByRole('button', { name: '添加子进度', exact: true }).click();
  await expect(task).toHaveClass(/task-waiting/);
  await expect(direction.getByLabel('方向状态：中心调整方向')).toContainText('自动');
  await expect(other).toHaveClass(/step-done/);
  await direction.getByRole('button', { name: '添加子进度', exact: true }).click();
  await page.getByLabel('子进度标题').fill('第二轮验证');
  await page.getByRole('dialog').getByRole('button', { name: '添加子进度', exact: true }).click();
  await expect(direction.locator('.substep')).toHaveCount(2);
  await expect(other.locator('.substep')).toHaveCount(0);
  await direction.locator('.substep').nth(1).getByRole('button', { name: '上移子进度' }).click();
  await expect(direction.locator('.substep-title').first()).toHaveText('第二轮验证');
  await direction.getByRole('button', { name: '下移方向', exact: true }).click();
  await expect(task.locator('.step-title').first()).toHaveText('独立验证方向');
  await page.reload();
  await expect(direction.locator('.substep-title').first()).toHaveText('第二轮验证');
  await expect(direction.locator('.substep .image-thumbnail img')).toBeVisible();
  await direction.locator('.substep .image-thumbnail').click();
  await expect(page.getByRole('dialog', { name: '图片预览' })).toBeVisible();
  await page.getByRole('button', { name: '关闭图片预览' }).click();
  await direction.locator('.substeps-toggle').click();
  await expect(direction.locator('.substeps')).toBeHidden();
  await page.locator('.followup-item').filter({ hasText: '第一轮验证' }).click();
  await expect(direction.locator('.substeps')).toBeVisible();
  await expect(direction.locator('.substep-content')).toHaveText(content.trim());
  await expect(direction.locator('.substep .full-record, .substep-content.preview')).toHaveCount(0);
  expect(await direction.locator('.substep-content').evaluate(el => el.scrollHeight <= el.clientHeight)).toBe(true);
  expect(await page.evaluate(() => window.substepInjected)).toBeUndefined();
  await page.getByLabel('搜索任务或进度').fill('子进度搜索关键字');
  await expect(task).toBeVisible();
  await page.getByLabel('搜索任务或进度').fill('');
  await direction.locator('.substep').first().getByRole('button', { name: '编辑子进度', exact: true }).click();
  await page.getByLabel('子进度标题').fill('第二轮复核');
  await page.getByRole('button', { name: '保存修改', exact: true }).click();
  await direction.getByRole('button', { name: '编辑方向', exact: true }).click();
  await expect(page.locator('.direction-status-hint')).toBeVisible();
  await page.getByLabel('进度记录').fill('原来的进度内容保留，补充方向说明');
  await page.getByRole('button', { name: '保存修改', exact: true }).click();
  await expect(direction.locator('.substep')).toHaveCount(2);
  await direction.getByRole('button', { name: '标记完成：第一轮验证', exact: true }).click();
  await direction.getByLabel('子进度状态：第二轮复核').click();
  await page.getByRole('menuitemradio', { name: '已完成', exact: true }).click();
  await expect(task).toHaveClass(/task-done/);
  await expect(direction.locator('.substep-done')).toHaveCount(2);
  await expect(page.locator('.progress-ring strong')).toHaveText('100%');
  await direction.getByRole('button', { name: '恢复未完成：第一轮验证', exact: true }).click();
  await expect(task).toHaveClass(/task-active/);
  await expect(direction.locator('.substeps-toggle')).toContainText('1 / 2 完成');
  await page.getByRole('button', { name: '收起日历栏', exact: true }).click();
  await expect.poll(async () => Math.round((await page.locator('.sidebar').boundingBox()).width)).toBe(60);
  await page.screenshot({ path: 'test-results/subprogress-desktop.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: '切换明暗主题' }).click();
  await page.screenshot({ path: 'test-results/subprogress-light.png', fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/subprogress-mobile.png', fullPage: true, animations: 'disabled' });
  await direction.getByRole('button', { name: '删除方向', exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('2 条子进度');
  await page.getByRole('button', { name: '保留', exact: true }).click();
  await direction.locator('.substep').first().getByRole('button', { name: '删除子进度', exact: true }).click();
  await page.getByRole('button', { name: '确认删除', exact: true }).click();
  await expect(direction.locator('.substep')).toHaveCount(1);
  await expect(other).toHaveClass(/step-done/);
  await removeTask(page, taskId);
  expect(errors).toEqual([]);
});

test('child drafts survive failed saves and a stale editor preserves both the saved record and unsaved input', async ({ page, context }) => {
  const taskId = await seed(page, '子进度草稿测试');
  await page.goto('/');
  const direction = page.locator(`[data-task-id="${taskId}"] .step`).first();
  await direction.getByRole('button', { name: '添加子进度', exact: true }).click();
  await page.getByLabel('子进度标题').fill('不会丢失的子进度');
  await page.getByLabel('进度记录').fill('保存失败也保留输入');
  await page.route('**/api/commands', route => route.abort('failed'));
  await page.getByRole('dialog').getByRole('button', { name: '添加子进度', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('暂时无法保存');
  await page.reload();
  await page.unroute('**/api/commands');
  await direction.getByRole('button', { name: '添加子进度', exact: true }).click();
  await expect(page.getByLabel('子进度标题')).toHaveText('不会丢失的子进度');
  await expect(page.getByLabel('进度记录')).toHaveText('保存失败也保留输入');
  await page.getByRole('dialog').getByRole('button', { name: '添加子进度', exact: true }).click();
  await direction.getByRole('button', { name: '编辑子进度', exact: true }).click();
  await page.getByLabel('进度记录').fill('窗口 A 的草稿');
  const other = await context.newPage(); await other.goto('/');
  await other.locator(`[data-task-id="${taskId}"]`).getByRole('button', { name: '编辑子进度', exact: true }).click();
  await other.getByLabel('进度记录').fill('窗口 B 已保存');
  await other.getByRole('button', { name: '保存修改', exact: true }).click();
  await page.getByRole('button', { name: '保存修改', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('其他窗口更新了内容');
  await expect(page.getByLabel('进度记录')).toHaveText('窗口 A 的草稿');
  const saved = await (await page.request.get('/api/state')).json();
  expect(saved.tasks.find(task => task.id === taskId).steps[0].substeps[0].content).toBe('窗口 B 已保存');
  await removeTask(page, taskId);
});
