import { test, expect } from '@playwright/test';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

test('completed turns turn green across directions without interrupting input or changing manual progress', async ({ page }) => {
  let state = await (await page.request.get('/api/state')).json();
  const run = async command => {
    const response = await page.request.post('/api/commands', { data: { revision: state.revision, command } });
    expect(response.ok()).toBeTruthy(); state = await response.json();
  };
  await run({ type: 'create-task', title: '终端关联验证', date: '2026-10-09' });
  const taskId = state.tasks.at(-1).id;
  await run({ type: 'create-step', taskId, title: '当前研究', content: '我手动维护的进度', status: 'active' });
  await run({ type: 'create-step', taskId, title: '另一个研究方向', status: 'active' });
  const [first, second] = state.tasks.at(-1).steps;
  const terminals = [first, second].map(step => ({ id: `terminal-${step.id}`, stepId: step.id, status: 'running', activity: { state: 'unknown' } }));
  const input = [], errors = [];
  let connections = 0, statusUnavailable = false;
  await page.route('**/api/state', route => route.fulfill({ json: { ...state, tasks: state.tasks.filter(t => t.id === taskId) } }));
  await page.route('**/api/workbench/bootstrap', route => route.fulfill({ json: { token: 'test-only', projects: [], terminals } }));
  await page.route('**/api/workbench/status', route => route.fulfill(statusUnavailable ? { status: 503, json: { error: 'Status temporarily unavailable' } } : { json: { terminals } }));
  await page.routeWebSocket(/\/api\/workbench\/attach\?/, ws => {
    connections++;
    ws.onMessage(raw => { const message = JSON.parse(String(raw)); if (message.type === 'input') input.push(message.data); });
    ws.send(JSON.stringify({ type: 'snapshot', terminal: terminals[0], data: 'Existing output stays here\r\n' }));
  });
  await page.addInitScript(id => { localStorage.setItem('procision-theme', 'dark'); localStorage.setItem('precision-direction', id); }, first.id);
  page.on('pageerror', error => errors.push(error.message));
  await page.clock.install();
  await page.goto('/');
  const firstTab = page.locator(`[data-direction="${first.id}"]`), secondTab = page.locator(`[data-direction="${second.id}"]`);
  const badge = page.locator('.wb-status'), textarea = page.locator('.wb-terminal textarea');
  await expect(page.locator('.xterm-rows')).toContainText('Existing output stays here');
  await textarea.focus();
  await page.evaluate(() => { window.originalTerminal = document.querySelector('.xterm'); });
  await page.keyboard.type('draft');
  terminals[1].activity = { state: 'completed', turnId: 'second-done', completedAt: 123 };
  await page.clock.runFor(5100);
  await expect(secondTab).toContainText('本轮已完成');
  await expect(secondTab).toHaveClass(/is-complete/);
  await expect(firstTab).not.toHaveClass(/is-complete/);
  await expect(firstTab).toHaveClass(/selected/);
  await expect(textarea).toBeFocused();
  terminals[0].activity = { state: 'completed', turnId: 'first-done', completedAt: 124 };
  await page.clock.runFor(5100);
  await expect(badge).toHaveText('本轮已完成');
  await expect(firstTab).toHaveClass(/is-complete/);
  await expect(badge).toHaveCSS('color', 'rgb(134, 239, 172)');
  await expect(firstTab).toHaveCSS('background-color', 'rgb(18, 49, 35)');
  await expect(textarea).toBeFocused();
  await page.keyboard.type(' more');
  expect(input.join('')).toBe('draft more');
  await page.screenshot({ path: 'test-results/workbench-completed-dark.png' });
  await page.getByRole('button', { name: '切换明暗主题', exact: true }).click();
  await expect(badge).toHaveCSS('color', 'rgb(22, 101, 52)');
  await expect(firstTab).toHaveCSS('background-color', 'rgb(231, 247, 235)');
  await page.screenshot({ path: 'test-results/workbench-completed-light.png' });
  statusUnavailable = true;
  await page.clock.runFor(5100);
  await expect(firstTab).not.toHaveClass(/is-complete/);
  await expect(secondTab).not.toHaveClass(/is-complete/);
  statusUnavailable = false;
  for (const activity of [{ state: 'unknown', turnId: 'new-turn' }, { state: 'working' }, { state: 'interrupted' }, { state: 'failed' }, { state: 'idle' }]) {
    terminals[0].activity = activity;
    await page.clock.runFor(5100);
    await expect(firstTab).not.toHaveClass(/is-complete/);
    await expect(badge).not.toHaveText('本轮已完成');
  }
  terminals[0].activity = { state: 'completed', completedAt: 124 };
  terminals[0].status = 'exited';
  await page.clock.runFor(5100);
  await expect(badge).toHaveText('终端已退出');
  await expect(badge).not.toHaveClass(/is-complete/);
  expect(await page.evaluate(() => window.originalTerminal === document.querySelector('.xterm'))).toBe(true);
  expect(connections).toBe(1); expect(errors).toEqual([]);
  expect(await (await page.request.get('/api/state')).json()).toEqual(state);
});

test('terminal and empty workspace follow the saved theme without replacing the connection or output', async ({ page }) => {
  let state = await (await page.request.get('/api/state')).json();
  const run = async command => {
    const response = await page.request.post('/api/commands', { data: { revision: state.revision, command } });
    expect(response.ok()).toBeTruthy(); state = await response.json();
  };
  await run({ type: 'create-task', title: '终端关联验证', date: '2026-10-09' });
  const taskId = state.tasks.at(-1).id;
  await run({ type: 'create-step', taskId, title: '主题终端', status: 'active' });
  const stepId = state.tasks.at(-1).steps.at(-1).id;
  await run({ type: 'create-step', taskId, title: '尚未连接', status: 'active' });
  const emptyId = state.tasks.at(-1).steps.at(-1).id;
  const terminal = { id: 'theme-terminal', stepId, status: 'running' };
  const messages = [], errors = [];
  let connections = 0, socket;
  await page.route('**/api/state', route => route.fulfill({ json: { ...state, tasks: state.tasks.filter(t => t.id === taskId) } }));
  await page.route('**/api/workbench/bootstrap', route => route.fulfill({ json: { token: 'test-only', projects: [], terminals: [terminal] } }));
  await page.route('**/api/workbench/status', route => route.fulfill({ json: { terminals: [terminal] } }));
  await page.routeWebSocket(/\/api\/workbench\/attach\?/, ws => {
    connections++; socket = ws;
    ws.onMessage(message => messages.push(JSON.parse(String(message))));
    ws.send(JSON.stringify({ type: 'snapshot', terminal, data: 'Preserved session output\r\n\x1b[32mReady\x1b[0m\r\n' }));
  });
  await page.addInitScript(() => localStorage.setItem('procision-theme', 'light'));
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  const rows = page.locator('.wb-terminal .xterm-rows');
  const surface = page.locator('.wb-surface');
  const toggle = page.getByRole('button', { name: '切换明暗主题', exact: true });
  await expect(rows).toContainText('Preserved session output');
  await expect(rows).toHaveCSS('color', 'rgb(29, 42, 59)');
  await expect(surface).toHaveCSS('background-color', 'rgb(248, 250, 252)');
  await expect(rows.locator('.xterm-fg-2').first()).toHaveCSS('color', 'rgb(35, 119, 67)');
  await page.evaluate(() => { window.originalTerminal = document.querySelector('.wb-terminal .xterm'); });
  await toggle.click();
  await expect(surface).toHaveCSS('background-color', 'rgb(10, 16, 26)');
  await expect(rows).toHaveCSS('color', 'rgb(219, 229, 242)');
  await page.locator(`[data-direction="${emptyId}"]`).click();
  await expect(page.locator('.wb-empty')).toBeVisible();
  await toggle.click();
  await expect(surface).toHaveCSS('background-color', 'rgb(248, 250, 252)');
  await expect(page.locator('.wb-empty')).toHaveCSS('color', 'rgb(29, 42, 59)');
  await page.screenshot({ path: 'test-results/workbench-light-empty.png' });
  await page.locator(`[data-direction="${stepId}"]`).click();
  await expect(rows).toHaveCSS('color', 'rgb(29, 42, 59)');
  await expect(rows).toContainText('Preserved session output');
  expect(await page.evaluate(() => window.originalTerminal === document.querySelector('.wb-terminal .xterm'))).toBe(true);
  socket.send(JSON.stringify({ type: 'output', data: 'Still connected\r\n' }));
  await expect(rows).toContainText('Still connected');
  await page.locator('.wb-terminal .xterm-helper-textarea').press('x');
  await expect.poll(() => messages.some(m => m.type === 'input' && m.data === 'x')).toBe(true);
  expect(connections).toBe(1); expect(errors).toEqual([]);
  expect(await page.evaluate(() => localStorage.getItem('procision-theme'))).toBe('light');
  await page.screenshot({ path: 'test-results/workbench-light-terminal.png' });
});

test.afterEach(async ({ request }) => {
  let state = await (await request.get('/api/state')).json();
  for (const task of state.tasks.filter(t => t.title === '终端关联验证')) {
    state = await (await request.post('/api/commands', { data: { revision: state.revision, command: { type: 'delete-task', taskId: task.id } } })).json();
  }
});

test('workspace divider resizes both panes, remembers width and keeps the terminal connected', async ({ page }) => {
  let state = await (await page.request.get('/api/state')).json();
  const run = async command => {
    const response = await page.request.post('/api/commands', { data: { revision: state.revision, command } });
    expect(response.ok()).toBeTruthy(); state = await response.json();
  };
  await run({ type: 'create-task', title: '终端关联验证', date: '2026-10-09' }); const taskId = state.tasks.at(-1).id;
  await run({ type: 'create-step', taskId, title: '调整分栏继续研究', status: 'active' }); const stepId = state.tasks.at(-1).steps[0].id;
  const terminal = { id: 'resize-terminal', stepId, status: 'running' }, messages = [], errors = [];
  let connections = 0;
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/api/state', route => route.fulfill({ json: { ...state, tasks: state.tasks.filter(t => t.id === taskId) } }));
  await page.route('**/api/workbench/bootstrap', route => route.fulfill({ json: { token: 'test-only', projects: [], terminals: [terminal] } }));
  await page.route('**/api/workbench/status', route => route.fulfill({ json: { terminals: [terminal] } }));
  await page.routeWebSocket(/\/api\/workbench\/attach\?/, ws => {
    connections++;
    ws.onMessage(raw => messages.push(JSON.parse(String(raw))));
    ws.send(JSON.stringify({ type: 'snapshot', terminal, data: 'Research remains connected\r\n' }));
  });
  await page.setViewportSize({ width: 1680, height: 1000 }); await page.goto('/');
  const handle = page.getByRole('separator', { name: '调整进度区与 Codex 工作区宽度' });
  const left = page.locator('.task-workspace'), right = page.locator('#workbench-root');
  const width = async locator => (await locator.boundingBox()).width;
  const savedWidth = () => page.evaluate(() => localStorage.getItem('precision-workbench-left-width'));
  const drag = async delta => {
    const box = await handle.boundingBox();
    await page.mouse.move(box.x + box.width / 2, box.y + 100); await page.mouse.down();
    await page.mouse.move(box.x + box.width / 2 + delta, box.y + 100, { steps: 12 });
  };
  const terminalFits = async () => {
    const screen = await page.locator('.xterm-screen').boundingBox(), surface = await page.locator('.wb-surface').boundingBox();
    return screen.x + screen.width < surface.x + surface.width && screen.y + screen.height < surface.y + surface.height;
  };
  await expect(page.locator('.xterm-rows')).toContainText('Research remains connected');
  await expect.poll(() => messages.some(m => m.type === 'resize')).toBe(true);
  await page.evaluate(() => { window.originalTerminal = document.querySelector('.wb-terminal .xterm'); });
  const initial = await width(left), initialRight = await width(right), initialCols = messages.filter(m => m.type === 'resize').at(-1).cols;
  const dividerBox = await handle.boundingBox(), leftBox = await left.boundingBox(), rightBox = await right.boundingBox();
  expect(dividerBox.x).toBeCloseTo(leftBox.x + leftBox.width, 0); expect(dividerBox.x + dividerBox.width).toBeCloseTo(rightBox.x, 0);
  await drag(180); await page.mouse.up();
  await expect.poll(() => width(left)).toBeCloseTo(initial + 180, 0);
  expect(await width(right)).toBeCloseTo(initialRight - 180, 0);
  await expect.poll(() => messages.filter(m => m.type === 'resize').at(-1)?.cols).toBeLessThan(initialCols);
  await expect.poll(terminalFits).toBe(true);
  await handle.press('ArrowLeft');
  await expect.poll(() => width(left)).toBeCloseTo(initial + 164, 0);
  const preference = await savedWidth();
  await drag(-90); await page.keyboard.press('Escape'); await page.mouse.up();
  await expect.poll(() => width(left)).toBeCloseTo(initial + 164, 0);
  expect(await savedWidth()).toBe(preference);
  await page.getByRole('button', { name: '切换明暗主题', exact: true }).click();
  await expect.poll(() => width(left)).toBeCloseTo(initial + 164, 0);
  await page.locator('[data-wb-mode="progress"]').click(); await expect(handle).not.toBeVisible();
  await page.locator('[data-wb-mode="cli"]').click(); await expect(handle).toBeVisible();
  expect(await width(left)).toBeCloseTo(initial + 164, 0);
  expect(await page.evaluate(() => window.originalTerminal === document.querySelector('.wb-terminal .xterm'))).toBe(true);
  await page.getByRole('button', { name: '展开右栏', exact: true }).click();
  await drag(70); await page.mouse.up();
  expect(await width(left)).toBeCloseTo(initial + 234, 0);
  await page.getByRole('button', { name: '收起右栏', exact: true }).click();
  await handle.press('End');
  expect(await width(right)).toBeCloseTo(380, 0); await expect.poll(terminalFits).toBe(true);
  const widePreference = await savedWidth();
  await page.setViewportSize({ width: 1060, height: 720 });
  await expect.poll(() => width(right)).toBeGreaterThanOrEqual(379);
  expect(await savedWidth()).toBe(widePreference);
  await page.locator('#sidebar-resizer').press('End');
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect.poll(terminalFits).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 }); await expect(handle).not.toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.setViewportSize({ width: 1920, height: 1080 });
  await expect.poll(() => width(left)).toBeCloseTo(Number(widePreference), 0);
  expect(connections).toBe(1);
  await page.reload();
  await expect(page.locator('.xterm-rows')).toContainText('Research remains connected');
  expect(await width(left)).toBeCloseTo(Number(widePreference), 0);
  await handle.dblclick(); expect(await savedWidth()).toBeNull();
  expect(await width(left)).toBeCloseTo(Math.min(420, Math.max(300, await width(page.locator('.workspace-columns')) * .27)), 0);
  await handle.press('Home'); expect(await width(left)).toBeCloseTo(300, 0);
  await page.locator('.wb-terminal textarea').press('x');
  await expect.poll(() => messages.some(m => m.type === 'input' && m.data === 'x')).toBe(true);
  await expect.poll(terminalFits).toBe(true);
  expect(connections).toBe(2); expect(errors).toEqual([]);
  expect(await (await page.request.get('/api/state')).json()).toEqual(state);
  await page.screenshot({ path: 'test-results/workbench-resizable-panes.png' });
});

test('terminal keeps its last row visible and forwards question navigation without triggering page shortcuts', async ({ page }) => {
  let state = await (await page.request.get('/api/state')).json();
  const run = async command => { const r = await page.request.post('/api/commands', { data: { revision: state.revision, command } }); expect(r.ok()).toBeTruthy(); state = await r.json(); };
  await run({ type: 'create-task', title: '终端关联验证', date: '2026-10-09' }); const taskId = state.tasks.at(-1).id;
  await run({ type: 'create-step', taskId, title: '提问与滚动验证', content: '左侧文字第一行\n\n第二行：保留空行', status: 'active' }); const stepId = state.tasks.at(-1).steps[0].id;
  const terminal = { id: 'question-terminal', stepId, status: 'running' }, input = [];
  let socket;
  const snapshot = Array.from({ length: 240 }, (_, i) => `Research output ${i + 1}\r\n`).join('') + 'ANSWER INPUT AT BOTTOM';
  await page.route('**/api/workbench/bootstrap', r => r.fulfill({ json: { token: 'fixture', projects: [], terminals: [terminal] } }));
  await page.route('**/api/workbench/status', r => r.fulfill({ json: { terminals: [terminal] } }));
  await page.routeWebSocket(/\/api\/workbench\/attach\?/, ws => {
    socket = ws;
    ws.onMessage(raw => { const message = JSON.parse(String(raw)); if (message.type === 'input') input.push(message.data); });
    ws.send(JSON.stringify({ type: 'snapshot', data: snapshot, terminal }));
  });
  await page.goto('/'); await page.locator(`[data-direction="${stepId}"]`).click();
  await expect(page.locator('.xterm-rows')).toContainText('ANSWER INPUT AT BOTTOM');
  for (const viewport of [{ width: 1440, height: 900 }, { width: 1280, height: 720 }, { width: 1920, height: 1080 }]) {
    await page.setViewportSize(viewport);
    await expect.poll(async () => {
      const screen = await page.locator('.xterm-screen').boundingBox(), surface = await page.locator('.wb-surface').boundingBox();
      return screen.y + screen.height <= surface.y + surface.height - 1 && screen.x + screen.width <= surface.x + surface.width - 1;
    }).toBe(true);
  }
  const textarea = page.locator('.wb-terminal textarea'); await textarea.focus();
  for (const [key, value] of [['ArrowUp', '\x1b[A'], ['ArrowDown', '\x1b[B'], ['ArrowLeft', '\x1b[D'], ['ArrowRight', '\x1b[C'], ['Shift+ArrowUp', '\x1b[1;2A'], ['Tab', '\t'], ['Shift+Tab', '\x1b[Z'], ['Shift+Enter', '\x1b\r'], ['Shift+Enter', '\x1b\r'], ['Enter', '\r'], ['Escape', '\x1b'], ['n', 'n'], ['/', '/']]) {
    const count = input.length; await textarea.press(key); await expect.poll(() => input.slice(count).join('')).toBe(value);
    await expect(textarea).toBeFocused();
  }
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.locator(`[data-step-id="${stepId}"] > .step-main > .step-content`).evaluate(element => {
    element.tabIndex = -1; element.focus();
    const range = document.createRange(); range.selectNodeContents(element);
    const selection = window.getSelection(); selection.removeAllRanges(); selection.addRange(range);
  });
  await page.keyboard.press('Control+c'); await textarea.focus();
  for (const shortcut of ['Control+v', 'Control+Shift+v', 'Shift+Insert']) {
    const count = input.length; await textarea.press(shortcut);
    await expect.poll(() => input.slice(count).join('')).toBe('左侧文字第一行\x1b\r\x1b\r第二行：保留空行');
  }
  const pasteCount = input.length;
  await textarea.evaluate(element => {
    const clipboard = new DataTransfer(); clipboard.setData('text/plain', '右键粘贴\r\n保留换行');
    element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: clipboard, bubbles: true, cancelable: true }));
  });
  await expect.poll(() => input.slice(pasteCount).join('')).toBe('右键粘贴\x1b\r保留换行');
  expect(input).not.toContain('\x16');
  await expect(page.locator('#editor')).not.toBeVisible();
  await page.locator('.wb-terminal').hover(); await page.mouse.wheel(0, -10000);
  await expect(page.locator('.xterm-rows')).not.toContainText('ANSWER INPUT AT BOTTOM');
  const track = page.locator('.xterm-scrollable-element > .scrollbar.vertical'), slider = track.locator('.slider');
  const box = await track.boundingBox(), thumb = await slider.boundingBox();
  await page.mouse.move(thumb.x + thumb.width / 2, thumb.y + thumb.height / 2); await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height - 1, { steps: 12 }); await page.mouse.up();
  await expect(page.locator('.xterm-rows')).toContainText('ANSWER INPUT AT BOTTOM');
  await page.locator('.wb-terminal').hover(); await page.mouse.wheel(0, -10000);
  await expect(page.locator('.xterm-rows')).not.toContainText('ANSWER INPUT AT BOTTOM');
  await page.locator('[data-wb="bottom"]').click();
  await expect(page.locator('.xterm-rows')).toContainText('ANSWER INPUT AT BOTTOM'); await expect(textarea).toBeFocused();
  await expect(page.locator('.wb-key-hint')).toHaveText('Shift + Enter 换行 · Enter 提交');
  socket.send(JSON.stringify({ type: 'readonly' }));
  await expect(page.locator('.xterm-rows')).toContainText('此处仅查看');
  const count = input.length;
  await textarea.press('Shift+Enter'); await textarea.press('Enter'); await textarea.press('Control+v');
  await page.waitForTimeout(100); expect(input.length).toBe(count);
  await page.screenshot({ path: 'test-results/terminal-last-row.png' });
});

test('Ctrl+C copies terminal selection, never interrupts on copy failure, and passes through only without selection', async ({ page }) => {
  let state = await (await page.request.get('/api/state')).json();
  const run = async command => {
    const response = await page.request.post('/api/commands', { data: { revision: state.revision, command } });
    expect(response.ok()).toBeTruthy(); state = await response.json();
  };
  await run({ type: 'create-task', title: '终端关联验证', date: '2026-10-09' }); const taskId = state.tasks.at(-1).id;
  await run({ type: 'create-step', taskId, title: '复制终端内容', status: 'active' }); const stepId = state.tasks.at(-1).steps[0].id;
  const terminal = { id: 'copy-terminal', stepId, status: 'running' }, input = [], errors = [];
  let connections = 0, socket;
  await page.route('**/api/state', route => route.fulfill({ json: { ...state, tasks: state.tasks.filter(t => t.id === taskId) } }));
  await page.route('**/api/workbench/bootstrap', route => route.fulfill({ json: { token: 'fixture', projects: [], terminals: [terminal] } }));
  await page.route('**/api/workbench/status', route => route.fulfill({ json: { terminals: [terminal] } }));
  await page.routeWebSocket(/\/api\/workbench\/attach\?/, ws => {
    connections++; socket = ws;
    ws.onMessage(raw => { const message = JSON.parse(String(raw)); if (message.type === 'input') input.push(message.data); });
    ws.send(JSON.stringify({ type: 'snapshot', terminal, data: '\x1b[32m研究结果：中文与 English\x1b[0m\r\n第二行：保留换行 123\r\nContinue here > ' }));
  });
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  const rows = page.locator('.xterm-rows > div');
  await expect(rows.nth(0)).toContainText('研究结果：中文与 English');
  const selected = page.locator('.xterm-selection > div');
  const selectOutput = async () => {
    const first = await rows.nth(0).boundingBox(), second = await rows.nth(1).boundingBox();
    await page.mouse.move(first.x + 1, first.y + first.height / 2); await page.mouse.down();
    await page.mouse.move(second.x + second.width - 2, second.y + second.height / 2, { steps: 8 }); await page.mouse.up();
    await expect(selected.first()).toBeVisible();
  };
  const clipboard = () => page.evaluate(async () => (await navigator.clipboard.readText()).replace(/\r\n/g, '\n'));
  const expected = '研究结果：中文与 English\n第二行：保留换行 123';
  await selectOutput();
  await page.keyboard.press('Control+c');
  await expect.poll(clipboard).toBe(expected);
  await expect(selected.first()).toBeVisible();
  await page.evaluate(() => navigator.clipboard.writeText('sentinel'));
  await page.keyboard.press('Control+Shift+c');
  await expect.poll(clipboard).toBe(expected);
  expect(input).toEqual([]);
  // Rejecting clipboard access must never fall back to sending ETX to the CLI.
  await page.evaluate(() => {
    window.originalClipboardWrite = navigator.clipboard.writeText.bind(navigator.clipboard);
    navigator.clipboard.writeText = () => Promise.reject(new DOMException('Clipboard denied', 'NotAllowedError'));
  });
  await page.keyboard.press('Control+c');
  await expect(page.locator('#toast')).toContainText('未向终端发送中断信号');
  await expect(selected.first()).toBeVisible(); expect(input).toEqual([]);
  await page.evaluate(() => { navigator.clipboard.writeText = window.originalClipboardWrite; });
  const inputRow = await rows.nth(2).boundingBox();
  await page.mouse.click(inputRow.x + 15, inputRow.y + inputRow.height / 2);
  await expect(selected).toHaveCount(0);
  await page.keyboard.press('Control+Shift+c');
  expect(await clipboard()).toBe(expected); expect(input).toEqual([]);
  await page.keyboard.press('Control+c');
  await expect.poll(() => input).toEqual(['\x03']);
  // Copy remains usable in a read-only connection as well.
  socket.send(JSON.stringify({ type: 'readonly' }));
  await expect(page.locator('.xterm-rows')).toContainText('此处仅查看');
  await selectOutput();
  await page.evaluate(() => navigator.clipboard.writeText('sentinel'));
  await page.keyboard.press('Control+c');
  await expect.poll(clipboard).toBe(expected);
  expect(input).toEqual(['\x03']); expect(connections).toBe(1); expect(errors).toEqual([]);
  expect(await (await page.request.get('/api/state')).json()).toEqual(state);
});

test('child directions open their own conversation from bottom-right buttons, inherit only directory defaults and retain separate terminals', async ({ page }) => {
  const project = resolve('test-results/child-ui-project'); mkdirSync(project, { recursive: true }); writeFileSync(resolve(project, 'README.md'), 'Shared research context');
  const parentSession = 'aaaaaaaa-1111-2222-3333-444444444444', childSession = 'bbbbbbbb-1111-2222-3333-444444444444';
  let state;
  const run = async command => {
    state = await (await page.request.get('/api/state')).json();
    const r = await page.request.post('/api/commands', { data: { revision: state.revision, command } });
    expect(r.ok()).toBeTruthy(); state = await r.json();
  };
  await run({ type: 'create-task', title: '终端关联验证', date: '2026-10-09' }); const taskId = state.tasks.at(-1).id;
  await run({ type: 'create-step', taskId, title: '状态空间分解', status: 'active' }); const parentId = state.tasks.at(-1).steps[0].id;
  await run({ type: 'bind-workspace', taskId, stepId: parentId, cwd: project, sessionId: parentSession, files: ['README.md'] });
  await run({ type: 'create-substep', taskId, stepId: parentId, title: '入场时机预测', content: '我的研究进度', status: 'active' }); const childId = state.tasks.at(-1).steps[0].substeps[0].id;
  await run({ type: 'create-substep', taskId, stepId: parentId, title: '预测误差诊断', status: 'waiting' }); const siblingId = state.tasks.at(-1).steps[0].substeps[1].id;
  const before = structuredClone(state.tasks.find(t => t.id === taskId)), activities = structuredClone(state.activities);
  const runtime = [{ id: 'parent-terminal', stepId: parentId, sessionId: parentSession, status: 'running' }], connections = new Map();
  let starts = 0;
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.route('**/api/workbench/bootstrap', route => route.fulfill({ json: { token: 'test-only', projects: [], terminals: runtime } }));
  await page.route('**/api/workbench/status', route => route.fulfill({ json: { terminals: runtime } }));
  await page.route('**/api/workbench/start', async route => {
    starts++; expect(route.request().postDataJSON()).toEqual({ stepId: childId, mode: 'new' });
    await run({ type: 'bind-workspace', taskId, stepId: childId, cwd: project, sessionId: childSession, files: ['README.md'] });
    const terminal = { id: 'child-terminal', stepId: childId, sessionId: childSession, status: 'running' }; runtime.push(terminal);
    await route.fulfill({ json: { terminal, state } });
  });
  await page.routeWebSocket(/\/api\/workbench\/attach\?/, ws => {
    const id = new URL(ws.url()).searchParams.get('stepId'), terminal = runtime.find(t => t.stepId === id);
    connections.set(id, (connections.get(id) || 0) + 1);
    ws.send(JSON.stringify({ type: 'snapshot', terminal, data: id === childId ? 'Independent entry timing research\r\n' : 'Parent research context\r\n' }));
  });
  await page.goto('/');
  await page.locator(`[data-direction="${parentId}"]`).click();
  await expect(page.locator('.wb-terminal:visible .xterm-rows')).toContainText('Parent research context');
  await expect(page.locator(`.wb-ongoing [data-direction="${childId}"]`)).toBeVisible();
  await expect(page.locator(`[data-direction="${siblingId}"]`)).toHaveCount(0);
  const parent = page.locator(`[data-step-id="${parentId}"]`), child = page.locator(`[data-substep-id="${childId}"]`);
  const parentButton = parent.locator('> .step-main > .wb-card-actions > button'), childButton = child.locator('.wb-connect-card');
  const bottomRight = async (container, button) => {
    const geometry = await container.evaluate(element => {
      const main = element.querySelector(':scope > .step-main, :scope > .substep-main');
      const card = main.getBoundingClientRect(), action = main.querySelector(':scope > .wb-card-actions > button').getBoundingClientRect();
      return { right: Math.abs(card.right - action.right), bottom: card.bottom - action.bottom, last: main.lastElementChild.classList.contains('wb-card-actions') };
    });
    expect(geometry.right).toBeLessThan(2); expect(geometry.bottom).toBeLessThanOrEqual(20); expect(geometry.last).toBe(true);
    await expect(button).toBeAttached();
  };
  await bottomRight(parent, parentButton); await bottomRight(child, childButton);
  await childButton.click();
  await expect(page.locator('.wb-console-title h2')).toHaveText('入场时机预测');
  await expect(page.locator('.wb-console-title .wb-eyebrow')).toContainText('状态空间分解');
  await expect(child).toHaveClass(/wb-current-direction/);
  await expect(page.locator('.wb-child-context')).toHaveText('子方向 · 独立会话');
  expect(starts).toBe(0);
  await page.getByRole('button', { name: '关联设置', exact: true }).click();
  await expect(page.locator('#wb-cwd')).toHaveValue(project);
  await expect(page.locator('#wb-session')).toHaveValue('');
  await expect(page.locator('#wb-pins')).toHaveValue('README.md');
  await page.getByRole('button', { name: '保存关联', exact: true }).click();
  await expect(page.locator('#workspace-settings')).not.toBeVisible();
  await page.locator('.wb-tools [data-wb="new"]').click();
  await expect(page.locator('.wb-terminal:visible .xterm-rows')).toContainText('Independent entry timing research');
  await parentButton.click();
  await expect(page.locator('.wb-terminal:visible .xterm-rows')).toContainText('Parent research context');
  await childButton.focus(); await childButton.press('Enter');
  await expect(page.locator('.wb-terminal:visible .xterm-rows')).toContainText('Independent entry timing research');
  await page.locator('[data-wb="progress"]').click();
  await expect(child).toBeInViewport();
  expect(connections.get(parentId)).toBe(1); expect(connections.get(childId)).toBe(1); expect(starts).toBe(1);
  await page.screenshot({ path: 'test-results/child-direction-desktop.png' });
  await page.locator(`[data-workbench-drag="${siblingId}"]`).dragTo(page.locator('.wb-surface'));
  await expect(page.locator(`.wb-manual [data-direction="${siblingId}"]`)).toHaveClass(/selected/);
  expect(starts).toBe(1);
  await page.reload();
  await expect(page.locator(`.wb-manual [data-direction="${siblingId}"]`)).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await childButton.click();
  await expect(page.locator('.wb-terminal:visible .xterm-rows')).toContainText('Independent entry timing research');
  await bottomRight(child, childButton);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/child-direction-mobile.png', fullPage: true });
  state = await (await page.request.get('/api/state')).json();
  const saved = state.tasks.find(t => t.id === taskId);
  expect(saved.steps[0].workspace).toEqual(before.steps[0].workspace);
  expect(saved.steps[0].substeps[0].workspace.sessionId).toBe(childSession);
  delete saved.steps[0].substeps[0].workspace;
  expect(saved).toEqual(before); expect(state.activities).toEqual(activities); expect(errors).toEqual([]);
});

test('split workspace keeps active children visible and dragging pins a direction without editing progress or launching a session', async ({ page }) => {
  let state = await (await page.request.get('/api/state')).json();
  const run = async command => {
    const r = await page.request.post('/api/commands', { data: { revision: state.revision, command } });
    expect(r.ok()).toBeTruthy(); state = await r.json();
  };
  await run({ type: 'create-task', title: '终端关联验证', date: '2026-10-09' });
  const taskId = state.tasks.at(-1).id;
  await run({ type: 'create-step', taskId, title: '包含进行中子进度的研究', status: 'waiting' });
  const activeId = state.tasks.at(-1).steps.at(-1).id;
  await run({ type: 'create-substep', taskId, stepId: activeId, title: '等待外部反馈', status: 'waiting' });
  await run({ type: 'create-substep', taskId, stepId: activeId, title: '继续第一轮研究', status: 'active' });
  await run({ type: 'create-step', taskId, title: '临时查阅的方向', content: '保留这段手动记录', status: 'waiting' });
  const waitingId = state.tasks.at(-1).steps.at(-1).id;
  const saved = structuredClone(state);
  const terminal = { id: 'split-terminal', stepId: activeId, status: 'running' };
  let connects = 0, starts = 0;
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.route('**/api/workbench/bootstrap', route => route.fulfill({ json: { token: 'test-only', projects: [], terminals: [terminal] } }));
  await page.route('**/api/workbench/status', route => route.fulfill({ json: { terminals: [terminal] } }));
  await page.route('**/api/workbench/start', route => { starts++; return route.abort(); });
  await page.routeWebSocket(/\/api\/workbench\/attach\?/, ws => {
    connects++;
    ws.send(JSON.stringify({ type: 'snapshot', terminal, data: 'Research remains connected\r\n' }));
  });
  await page.goto('/');
  await expect(page.locator(`.wb-ongoing [data-direction="${activeId}"]`)).toBeVisible();
  await page.locator(`.wb-ongoing [data-direction="${activeId}"]`).click();
  await expect(page.locator('.wb-child-context')).toContainText('继续第一轮研究');
  const task = page.locator(`[data-task-id="${taskId}"]`);
  await expect(task.locator('.task-title-line .status-chip')).toHaveText('进行中');
  await expect(page.locator(`[data-step-id="${activeId}"] > .step-main > .step-heading .status-chip`)).toHaveText('进行中');
  const left = await page.locator('.task-workspace').boundingBox(), right = await page.locator('#workbench-root').boundingBox();
  expect(left.x + left.width).toBeLessThanOrEqual(right.x); expect(Math.abs(left.y - right.y)).toBeLessThan(2);
  await expect(page.locator('.xterm-rows')).toContainText('Research remains connected');
  await page.locator(`[data-workbench-drag="${waitingId}"]`).dragTo(page.locator('.wb-surface'));
  await expect(page.locator(`.wb-manual [data-direction="${waitingId}"]`)).toHaveClass(/selected/);
  await expect(page.locator('.wb-console-title h2')).toHaveText('临时查阅的方向');
  await expect(page.locator(`[data-step-id="${waitingId}"]`)).toHaveClass(/wb-current-direction/);
  expect(await (await page.request.get('/api/state')).json()).toEqual(saved);
  expect(starts).toBe(0);
  await page.locator(`[data-direction="${activeId}"]`).click();
  await expect(page.locator('.xterm-rows')).toContainText('Research remains connected');
  expect(connects).toBe(1);
  await page.screenshot({ path: 'test-results/split-workbench-desktop.png' });
  await page.reload();
  await expect(page.locator(`.wb-manual [data-direction="${waitingId}"]`)).toBeVisible();
  await page.locator(`[data-direction="${waitingId}"]`).click();
  await page.getByRole('button', { name: '取消固定', exact: true }).click();
  await expect(page.locator(`[data-direction="${waitingId}"]`)).toHaveCount(0);
  // The click alternative is available on phones and for keyboard users.
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator(`[data-step-id="${waitingId}"] .wb-connect-card`).click();
  await expect(page.locator('.wb-console-title h2')).toHaveText('临时查阅的方向');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/split-workbench-mobile.png', fullPage: true });
  expect(await (await page.request.get('/api/state')).json()).toEqual(saved);
  await page.setViewportSize({ width: 1440, height: 1100 });
  await page.locator(`[data-direction="${activeId}"]`).click();
  const connectedBeforeEdit = connects;
  await page.evaluate(() => { window.terminalBeforeEdit = document.querySelector('.wb-terminal .xterm'); });
  const child = page.locator(`[data-step-id="${activeId}"]`).getByRole('button', { name: '子进度状态：等待外部反馈', exact: true });
  await child.click();
  await page.getByRole('menuitemradio', { name: '进行中', exact: true }).click();
  await expect(child).toHaveText('进行中');
  await expect(page.locator('.xterm-rows')).toContainText('Research remains connected');
  expect(connects).toBe(connectedBeforeEdit);
  expect(await page.evaluate(() => window.terminalBeforeEdit === document.querySelector('.wb-terminal .xterm'))).toBe(true);
  expect(starts).toBe(0); expect(errors).toEqual([]);
});

test('CLI workspace defaults, manual binding, safe file preview and journal remain independent', async ({ page }) => {
  const project = resolve('test-results/ui-project'); mkdirSync(project, { recursive: true }); writeFileSync(resolve(project, 'README.md'), '# 研究入口\n<script>window.previewExecuted=true</script>');
  let state = await (await page.request.get('/api/state')).json();
  const run = async command => { const r = await page.request.post('/api/commands', { data: { revision: state.revision, command } }); expect(r.ok()).toBeTruthy(); state = await r.json(); };
  await run({ type: 'create-task', title: '终端关联验证', date: '2026-10-09' }); const taskId = state.tasks.at(-1).id;
  await run({ type: 'create-step', taskId, title: '独立研究方向', content: '这是我手动整理的进度', status: 'active' }); const stepId = state.tasks.at(-1).steps[0].id;
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/'); await expect(page.locator('html')).toHaveAttribute('data-workbench', 'cli'); await expect(page.locator('html')).toHaveAttribute('data-insights', 'collapsed');
  await page.locator(`[data-direction="${stepId}"]`).click();
  await page.getByRole('button', { name: '关联设置', exact: true }).click();
  await page.getByLabel('工作目录', { exact: true }).fill(project);
  await page.getByLabel('关键文件', { exact: false }).fill('README.md');
  await page.getByRole('button', { name: '保存关联', exact: true }).click();
  await expect(page.locator('#workspace-settings')).not.toBeVisible();
  await expect(page.locator('.wb-location')).toContainText(project);
  await page.getByRole('button', { name: '相关文件', exact: true }).click();
  await page.locator('[data-file="README.md"]').click();
  await expect(page.locator('.wb-preview-text')).toContainText('<script>window.previewExecuted=true</script>'); expect(await page.evaluate(() => window.previewExecuted)).toBeUndefined();
  await page.getByRole('button', { name: '关闭文件预览' }).click();
  await page.reload(); await expect(page.locator('.wb-location')).toContainText(project);
  await page.getByRole('button', { name: '展开右栏', exact: true }).click(); await expect(page.getByRole('region', { name: '思考与结论' })).toBeVisible();
  await page.getByRole('button', { name: '收起右栏', exact: true }).click();
  await page.getByRole('button', { name: '记录进度', exact: true }).click(); await expect(page.locator('html')).toHaveAttribute('data-workbench', 'cli');
  await expect(page.locator(`[data-step-id="${stepId}"]`)).toBeVisible();
  const after = await (await page.request.get('/api/state')).json(); const direction = after.tasks.find(t => t.id === taskId).steps[0];
  expect(direction.content).toBe('这是我手动整理的进度'); expect(direction.status).toBe('active'); expect(direction.workspace.cwd).toBe(project); expect(direction.workspace.sessionId).toBe('');
  expect(errors).toEqual([]);
});

test('completed directions leave collaboration, retain their journal, and return when reopened; live terminals remain accessible', async ({ page }) => {
  let state = await (await page.request.get('/api/state')).json();
  const run = async command => {
    const response = await page.request.post('/api/commands', { data: { revision: state.revision, command } });
    expect(response.ok()).toBeTruthy(); state = await response.json();
  };
  await run({ type: 'create-task', title: '终端关联验证', date: '2026-10-09' });
  const taskId = state.tasks.at(-1).id;
  await run({ type: 'create-step', taskId, title: '已完成方向', content: '保留我的手动结论', status: 'done' });
  const doneId = state.tasks.at(-1).steps.at(-1).id;
  await run({ type: 'create-step', taskId, title: '汇总完成方向', status: 'active' });
  const autoId = state.tasks.at(-1).steps.at(-1).id;
  await run({ type: 'create-substep', taskId, stepId: autoId, title: '最后一步', status: 'done' });
  await run({ type: 'create-step', taskId, title: '继续研究', status: 'active' });
  const activeId = state.tasks.at(-1).steps.at(-1).id;
  await run({ type: 'create-step', taskId, title: '尚未开展', status: 'todo' });
  const todoId = state.tasks.at(-1).steps.at(-1).id;
  await run({ type: 'create-step', taskId, title: '等待外部反馈', status: 'waiting' });
  let runtime = [], socket;
  await page.route('**/api/state', route => route.fulfill({ json: { ...state, tasks: state.tasks.filter(t => t.id === taskId) } }));
  await page.route('**/api/workbench/bootstrap', route => route.fulfill({ json: { token: 'test-only', projects: [], terminals: runtime } }));
  await page.route('**/api/workbench/status', route => route.fulfill({ json: { terminals: runtime } }));
  await page.routeWebSocket(/\/api\/workbench\/attach\?/, ws => { socket = ws; });
  await page.addInitScript(id => localStorage.setItem('precision-direction', id), doneId);
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.locator('.wb-direction')).toHaveCount(1);
  await expect(page.locator('.wb-direction.selected')).toHaveAttribute('data-direction', activeId);
  await run({ type: 'set-step-status', taskId, stepId: activeId, status: 'done' });
  await page.reload();
  await expect(page.locator('.wb-direction')).toHaveCount(0);
  await expect(page.locator('.wb-project')).toHaveCount(0);
  await expect(page.locator('.wb-empty h3')).toHaveText('暂无进行中的方向');
  await expect(page.locator('.wb-tools')).toHaveCount(0);
  await page.getByRole('button', { name: '查看手动进度', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('data-workbench', 'progress');
  await expect(page.locator(`[data-step-id="${doneId}"]`)).toContainText('保留我的手动结论');
  await expect(page.locator(`[data-step-id="${doneId}"] .wb-connect-card`)).toBeVisible();
  await run({ type: 'set-step-status', taskId, stepId: doneId, status: 'active' });
  await page.reload();
  await page.locator('[data-wb-mode="cli"]').click();
  await expect(page.locator('.wb-direction')).toHaveCount(1);
  await expect(page.locator('.wb-direction.selected')).toHaveAttribute('data-direction', doneId);
  runtime = [{ id: 'test-terminal', stepId: autoId, status: 'running' }];
  await page.reload();
  await expect(page.locator('.wb-direction')).toHaveCount(2);
  await expect(page.locator('.wb-ongoing .wb-direction')).toHaveCount(1);
  await expect(page.locator('.wb-finishing .wb-direction')).toHaveCount(1);
  await page.locator(`[data-direction="${autoId}"]`).click();
  await expect(page.locator('.wb-direction.selected')).toContainText('已完成 · 终端运行中');
  await expect.poll(() => Boolean(socket)).toBeTruthy();
  runtime[0].status = 'stopping'; socket.send(JSON.stringify({ type: 'status', terminal: runtime[0] }));
  await expect(page.locator('.wb-direction.selected')).toContainText('已完成 · 正在退出');
  runtime[0].status = 'exited'; socket.send(JSON.stringify({ type: 'status', terminal: runtime[0] }));
  await expect(page.locator('.wb-direction')).toHaveCount(1);
  await expect(page.locator('.wb-direction.selected')).toHaveAttribute('data-direction', doneId);
  await expect(page.locator('.wb-terminal')).not.toBeVisible();
  expect(errors).toEqual([]);
  const saved = (await (await page.request.get('/api/state')).json()).tasks.find(t => t.id === taskId);
  expect(saved.steps).toHaveLength(5); expect(saved.steps[0].content).toBe('保留我的手动结论');
  expect(saved.steps.find(s => s.id === todoId).status).toBe('todo');
});
