import { test, expect } from './fixtures.mjs';
import { localDay } from '../../lib/domain.mjs';

test('daily task lifecycle, ordering, persistence, edits, search and deletion', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: '今天的进展，从这里开始' })).toBeVisible();
  await page.screenshot({ path: 'test-results/empty-desktop.png', fullPage: true });
  await page.getByRole('button', { name: '新建任务' }).click();
  await page.getByLabel('任务标题').fill('验证 AI 工作流');
  await page.getByLabel('补充说明').fill('任务目标：检查真实交互');
  const yesterday = new Date(); yesterday.setDate(yesterday.getDate() - 1);
  await page.getByLabel('所属日期').fill(localDay(yesterday));
  await page.getByRole('button', { name: '创建任务', exact: true }).click();
  const card = page.locator('.task-card').filter({ hasText: '验证 AI 工作流' });
  await expect(card).toBeVisible();
  await expect(card.locator('.carry-tag')).toHaveText('↳ 延续任务');
  const addStep = async (title, content, status) => {
    await card.getByRole('button', { name: '添加方向' }).click();
    await page.getByLabel('方向标题').fill(title);
    await page.getByLabel('进度记录').fill(content);
    await page.getByRole('radio', { name: status, exact: true }).check();
    await page.getByRole('dialog').getByRole('button', { name: '添加方向', exact: true }).click();
  };
  await addStep('需求确认', '第一行\n第二行 <script>window.injected=true</script>', '进行中');
  await addStep('验证输出', '检查多行输出和本地保存', '待跟进');
  await expect(card.locator('.step')).toHaveCount(2);
  await expect(card.locator('.task-title-line .status-chip')).toHaveText('进行中');
  await card.locator('.step').nth(1).getByRole('button', { name: '上移方向' }).click();
  await expect(card.locator('.step-title').first()).toHaveText('验证输出');
  await page.reload();
  await expect(card.locator('.step-title').first()).toHaveText('验证输出');
  expect(await page.evaluate(() => window.injected)).toBeUndefined();
  await expect(card.locator('.step-content').nth(1)).toHaveText('第一行\n第二行 <script>window.injected=true</script>');
  await card.getByRole('button', { name: '标记完成：需求确认', exact: true }).click();
  await card.getByRole('button', { name: '标记完成：验证输出', exact: true }).click();
  await expect(card).toHaveClass(/task-done/);
  await expect(card.locator('.step-done')).toHaveCount(2);
  await card.getByRole('button', { name: '恢复未完成：验证输出', exact: true }).click();
  await expect(card).toHaveClass(/task-active/);
  await card.locator('.step').first().getByRole('button', { name: '编辑方向', exact: true }).click();
  await page.getByLabel('方向标题').fill('验证输出已修订');
  await page.getByRole('button', { name: '保存修改' }).click();
  await expect(card.locator('.step-title').first()).toHaveText('验证输出已修订');
  await page.getByLabel('搜索任务或进度').fill('找不到的文字');
  await expect(page.getByRole('heading', { name: '这里暂时没有匹配的任务' })).toBeVisible();
  await page.getByLabel('搜索任务或进度').fill('第一行');
  await expect(card).toBeVisible();
  await page.getByLabel('搜索任务或进度').fill('');
  await card.getByRole('button', { name: '编辑任务', exact: true }).click();
  await page.getByLabel('任务标题').fill('验证后的工作流');
  await page.getByRole('button', { name: '保存修改' }).click();
  const edited = page.locator('.task-card').filter({ hasText: '验证后的工作流' });
  await expect(edited).toBeVisible();
  await edited.getByRole('button', { name: '删除任务', exact: true }).click();
  await page.getByRole('button', { name: '保留', exact: true }).click();
  await expect(edited).toBeVisible();
  await edited.getByRole('button', { name: '删除任务', exact: true }).click();
  await page.getByRole('button', { name: '确认删除', exact: true }).click();
  await expect(edited).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('demo mode is isolated and layouts work at desktop and phone sizes', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const before = await (await page.request.get('/api/state')).json();
  await page.goto('/?demo');
  await expect(page.locator('.task-card')).toHaveCount(3);
  await page.screenshot({ path: 'test-results/demo-desktop.png', fullPage: true });
  await page.getByRole('button', { name: '切换明暗主题' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await page.screenshot({ path: 'test-results/demo-light.png', fullPage: true });
  await page.getByRole('button', { name: '切换明暗主题' }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/demo-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: '新建任务' }).click();
  await page.getByLabel('任务标题').fill('手机示例');
  await page.getByRole('button', { name: '创建任务', exact: true }).click();
  await expect(page.locator('.task-card')).toHaveCount(4);
  await page.getByRole('button', { name: '退出示例' }).click();
  await expect(page.locator('.demo-notice')).toHaveCount(0);
  expect(await (await page.request.get('/api/state')).json()).toEqual(before);
  await expect(page.locator('.task-card').filter({ hasText: '手机示例' })).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('failed saves preserve the form and draft for retry', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: '新建任务' }).click();
  await page.getByLabel('任务标题').fill('不能丢失的草稿');
  await page.route('**/api/commands', route => route.abort('failed'));
  await page.getByRole('button', { name: '创建任务', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByLabel('任务标题')).toHaveText('不能丢失的草稿');
  await expect(page.getByRole('alert')).toContainText('暂时无法保存');
  await page.getByRole('button', { name: '取消', exact: true }).click();
  await page.getByRole('button', { name: '新建任务' }).click();
  await expect(page.getByLabel('任务标题')).toHaveText('不能丢失的草稿');
});
